apiVersion: apps/v1
kind: Deployment
metadata:
  name: section6-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: section6-nodejs
  template:
    metadata:
      labels:
        app: section6-nodejs
    spec:
      containers:
      - name: section6-nodejs
        image: raymondbaoly/section6-nodejs:prod
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: section6-nodejs
spec:
  selector:
    app: section6-nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
